INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Belando', 'Eloi', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Bernicia', 'Kimbuma', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Camarasa', 'Emma', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Decap', 'Carla', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Dessaints', 'Ange Lorenzo', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Disant', 'Eva', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Ducray Mestdagh', 'Chloé', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('El Hamdani', 'Sara', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Fernandez', 'Marcus', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Gerino', 'Diane', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Glorieux', 'Louise', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Goapper', 'Lola', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Hussard', 'Axel', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Jansens', 'Lou', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Jugiau', 'Antoine', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Kajeiou', 'Abdelhak', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Kerneur', 'Laurianne', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Lafon', 'Ilona', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Lalouette', 'Thaïs', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Le Ber', 'Lisa', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Leas', 'Botumbopha', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Lignac', 'Killian', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Masteau', 'Sophie', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Mousset', 'Cloé', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Muhire', 'Elise', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Palacin', 'Jade', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Pialleport', 'Lucas', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Prevoteau', 'Steaven', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Racha', 'Taibi', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Salim Koto', 'Amelle', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Scouarnec', 'Manon', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Teke', 'Berfin', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Thiam', 'Awa', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Tribert', 'Naya', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Viala', 'Macéo', 'Collège');
INSERT INTO Tuteur(nom, prenom, type_etablissement) VALUES('Zizi-Nacer', 'Kamil', 'Collège');
